[tool.poetry]
name = "boela-bench"
version = "0.1.0"
description = ""
authors = ["Taleh A. Agasiev <tallex13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
boela = "0.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
